// ============================================================
// SIGNALMAP TWITTER THREAD AUTO-POSTER
// Reads /tmp/marketing-content.json (generated by generate-content.js)
// Posts a thread to X/Twitter using Twitter API v2
//
// Required GitHub Secrets:
//   TWITTER_APP_KEY, TWITTER_APP_SECRET,
//   TWITTER_ACCESS_TOKEN, TWITTER_ACCESS_SECRET
// ============================================================

import { TwitterApi }  from 'twitter-api-v2';
import { readFileSync } from 'fs';

const client = new TwitterApi({
  appKey:            process.env.TWITTER_APP_KEY,
  appSecret:         process.env.TWITTER_APP_SECRET,
  accessToken:       process.env.TWITTER_ACCESS_TOKEN,
  accessSecret:      process.env.TWITTER_ACCESS_SECRET,
});

const rwClient = client.readWrite;

async function postThread(tweets) {
  let lastTweetId = null;
  const posted = [];

  for (const text of tweets) {
    // Enforce 280 char limit — trim gracefully
    const trimmed = text.length > 280 ? text.slice(0, 277) + '...' : text;

    const payload = lastTweetId
      ? { text: trimmed, reply: { in_reply_to_tweet_id: lastTweetId } }
      : { text: trimmed };

    const { data } = await rwClient.v2.tweet(payload);
    console.log(`  ✓ Tweet ${posted.length + 1}: ${data.id} — "${trimmed.slice(0, 60)}..."`);
    lastTweetId = data.id;
    posted.push(data.id);

    // Avoid rate limiting between tweets
    await new Promise(r => setTimeout(r, 1500));
  }

  return posted;
}

async function main() {
  // Validate credentials
  const required = ['TWITTER_APP_KEY', 'TWITTER_APP_SECRET', 'TWITTER_ACCESS_TOKEN', 'TWITTER_ACCESS_SECRET'];
  const missing  = required.filter(k => !process.env[k]);
  if (missing.length) {
    console.error(`Missing credentials: ${missing.join(', ')}`);
    console.error('Add these to GitHub Secrets. See MARKETING-SETUP.md.');
    process.exit(1);
  }

  // Load generated content
  let content;
  try {
    content = JSON.parse(readFileSync('/tmp/marketing-content.json', 'utf8'));
  } catch {
    console.error('No content file found. Run generate-content.js first.');
    process.exit(1);
  }

  const tweets = content.twitter_thread;
  if (!tweets?.length) {
    console.error('No tweets in content file');
    process.exit(1);
  }

  console.log(`Posting ${tweets.length}-tweet thread to Twitter...`);
  const posted = await postThread(tweets);
  console.log(`\n✓ Thread posted successfully. Root tweet: https://twitter.com/i/web/status/${posted[0]}`);
}

main().catch(err => {
  console.error('Twitter post failed:', err.message || err);
  // Don't exit 1 — marketing failures shouldn't block CI
  process.exit(0);
});
